### ISSUE TITLE
Death animations added/changed in 0.12 for all Ents, robo's, and both version of the Hercules beetles cause issues with morph

### ISSUE THREAD

**Issue by Lycaon3214** [Chaos-Awakens-Mod-Team/ChaosAwakens#127]
All other mobs added/changed work perfectly fine I don't know if this is an issues on Chaos awakens side but due to the animations the mobs listed aren't recognized at all by morph, the tendrils that are supposed to show you absorbing the mobs form do not show up what so ever. If this is an issue with morph it's self then I will let Ichun know

**Comment by RaveTr** [comment]
Morph has issues with GeckoLib entities in general. We probably won't add integration in 1.16.5 since we want to move forward ASAP. We will likely look into this once we're further into the development cycle of updates past 0.14.x.x+ (I.E. When we can start focusing more on misc. features).

Marking this as closed for now. IChun may feel free to add integration on his end if he so chooses. We may re-open this if there's a need for it (though highly unlikely, dw). Thanks for the report.
