### ISSUE TITLE
Robo jeffrey stop following you if you are in any area that is 2 blocks high

### ISSUE THREAD

**Issue by FunkyPotao** [Chaos-Awakens-Mod-Team/ChaosAwakens#141]
found out that robo jeffrey just stops following when you are in a 2 block high area, its like really cheesable like you can constantly hit it and it only does shockwaves

**Comment by RaveTr** [comment]
AI is being rewritten in 0.13.0.0.

That being said, Jeffery uses ray-tracing to check if it can see a target player from its eye-height (a basic system, which is used by most entities [vanilla/modded]). Since he's pretty tall, it'd be expected of him to do that.

But, don't worry, and refer to the first statement made in my reply. Everything will be getting a decent glowup next major update :)
