### ISSUE TITLE
Config option to turn off checking if dimensions are using Terraforged's ChunkGenerator

### ISSUE THREAD

**Issue by WolfBV** [Chaos-Awakens-Mod-Team/ChaosAwakens#19]
I don't know if this is the mod that's checking it, but the messages I get when generating a world go something like: 
"[Server thread/ERROR] [io.gi.ch.ChaosAwakens/]: java.lang.NoSuchMethodException: net.minecraft.world.gen.ChunkGenerator.codec(): Was unable to check if atum:atum is using Terraforged's ChunkGenerator."

**Comment by invalid2** [comment]
Yes, it is this mod that is doing the check. The check exists due to some incompatibilities that Terraforged can cause, I will make a more meaningful error/info message and make it so that you can deactivate it as well. The check itself will probably have to stay active, so you can actually play this mod with Terraforged.

**Comment by WolfBV** [comment]
Can the check be deactivated with a config option?

**Comment by invalid2** [comment]
Its not possible at the moment, but you will be able to deactivate the message in the next update

**Comment by Blackout03** [comment]
Fixed in [commit](https://github.com/Chaos-Awakens-Mod-Team/ChaosAwakens/commit/1a8b2e0a5be3d3b76815046b6db3840dbcdff3fc)
