### ISSUE TITLE
Hercules Beetle crashes game.

### ISSUE THREAD

**Issue by AdventureG147** [Chaos-Awakens-Mod-Team/ChaosAwakens#96]
I was attempting to spawn the Pacman entity from my mod, however I crashed, with the given error `ava.lang.NoClassDefFoundError: software/bernie/shadowed/eliotlash/molang/MolangParser`. At first I thought it was a problem with my mod, howver looking into the crash log seems to show that a hercules beetle had spawned, which is what made it crash. Also seems like the hercules beetle's animation broke, and the class seems to be missing?? Those are just theories and speculation based on what i read on the crash log, so I may be wrong.

I tried this once again, this time I did not try to spawn anything, and then crashed again, with the same error.

Crash log: 
[crash-2023-06-02_12.07.59-server.txt](https://github.com/ChaosAwakens/ChaosAwakens/files/11635006/crash-2023-06-02_12.07.59-server.txt)

**Comment by RaveTr** [comment]
Looks like you were using one of the alpha builds only available to donors/server boosters. The crash happened since when I compiled the alpha build, there was some leftover code I didn't clean up. The code causing this crash is no longer present anyway (refactor's made more progress, duh).

Anyway, that being said, alpha build will keep crashing a lot. Fixed for next update (and noted for future early-access releases).

**Comment by AdventureG147** [comment]
> Looks like you were using one of the alpha builds only available to donors/server boosters. The crash happened since when I compiled the alpha build, there was some leftover code I didn't clean up. The code causing this crash is no longer present anyway (refactor's made more progress, duh).
> 
> Anyway, that being said, alpha build will keep crashing a lot. Fixed for next update (and noted for future early-access releases).

Cool, thanks
